### ISSUE TITLE
Can't Make Account

### ISSUE THREAD

**Issue by RT1648** [sounddrill31/crave_aosp_builder#29]
Will You Please Explain How To Make A Account On "foss.crave.io" because i can't see any option to make an account when i visit the webpage.

Thanks

**Comment by DeclanShao** [comment]
I tried to visit https://foss.crave.io/app/#/signUp, but I found that they disabled account registration.

**Comment by RT1648** [comment]
> I tried to visit https://foss.crave.io/app/#/signUp, but I found that they disabled account registration.

Exactly, I tried Just Now Again

**Comment by sounddrill31** [comment]
Not related to the builder, closing

For an account, please contact the admins directly at https://discord.crave.io

@RT1648 @DeclanShao

**Comment by sounddrill31** [comment]
I really need to add an FAQ... someday

**Comment by RT1648** [comment]
> Not related to the builder, closing
> 
> For an account, please contact the admins directly at https://discord.crave.io
> 
> @RT1648 @DeclanShao
> 
> https://opendroid.pugzarecute.com/wiki/Crave_Devspace#Getting_a_foss.crave.io_account

Thank You For Responding!
It's a better idea to add FAQ in README or any sort of similar things.

**Comment by sounddrill31** [comment]
> > Not related to the builder, closing
> > For an account, please contact the admins directly at https://discord.crave.io
> > @RT1648 @DeclanShao
> > https://opendroid.pugzarecute.com/wiki/Crave_Devspace#Getting_a_foss.crave.io_account
> 
> Thank You For Responding! It's a better idea to add FAQ in README or any sort of similar things.

will do in the future, thanks!
