### ISSUE TITLE
Have a error with self host runner

### ISSUE THREAD

**Issue by MohamedDevvv** [sounddrill31/crave_aosp_builder#54]
Hi,
I have a error with create self host runner 
I got this error:

`Runner Started
Error: Warning: Identity file /home/runner/.ssh/crave_key_rsa not accessible: No such file or directory.
admin@localhost: Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]
Error: Warning: Identity file /home/runner/.ssh/crave_key_rsa not accessible: No such file or directory.
admin@localhost: Permission denied (publickey).
Error: Warning: Identity file /home/runner/.ssh/crave_key_rsa not accessible: No such file or directory.
admin@localhost: Permission denied (publickey).
Connecting to: adoring_germain for user ***
Services in this job can be accessed using the following:
Service      Remote  Access URL
---------  --------  -----------------------
ssh              22  ssh://localhost:32[8](https://github.com/MohamedDevvv/crave_builder/actions/runs/11317758297/job/31472043770#step:5:9)50
vscode         5899  vscode://localhost:5899
could not access users session, retrying using own key
Services in this job can be accessed using the following:
Service      Remote  Access URL
---------  --------  -----------------------
ssh              22  ssh://localhost:32850
vscode         58[9](https://github.com/MohamedDevvv/crave_builder/actions/runs/11317758297/job/31472043770#step:5:10)9  vscode://localhost:5899 `

Any solution pls

**Comment by sounddrill31** [comment]
Ignore the logspam, it should still work. 

Let me know if it doesn't

**Comment by MohamedDevvv** [comment]
it stuck and give this

Requested labels: self-hosted
Job defined at: MohamedDevvv/crave_aosp_builder/.github/workflows/selfhosted.yml@refs/heads/main
Waiting for a runner to pick up this job...

**Comment by MohamedDevvv** [comment]
I restarted the runner and it worked!
