### ISSUE TITLE
 crave_asop_builder

### ISSUE THREAD

**Issue by Failedmush** [sounddrill31/crave_aosp_builder#55]
I am using Crave Builder (not selfhost) but it keeps failing after 10 seconds 

this is the error https://github.com/Failedmush/crave_aosp_builder/actions/runs/11531544081
this is also my local mainfest https://github.com/Failedmush/local_manifestss
can I ask what am I doing wrong?

**Comment by sounddrill31** [comment]
Check the branch you entered, it doesn't look valid. 
![image](https://github.com/user-attachments/assets/dc209182-7730-4507-975b-a783403487f7)
