### ISSUE TITLE
Do you need crave token to build asop rom

### ISSUE THREAD

**Issue by Failedmush** [sounddrill31/crave_aosp_builder#56]
HI I wanted to ask if you needed crave token to build ASOP rom ?

is it normal to wait 6 hours without getting a build done? 

if I sign up to github enterprise does the runner excepend longer?

many thanks

**Comment by sounddrill31** [comment]
> HI I wanted to ask if you needed crave token to build ASOP rom ?

No, The team clarified that this was a bug in the official chat

> is it normal to wait 6 hours without getting a build done?

What do you mean by this?

> if I sign up to github enterprise does the runner excepend longer?

I don't think so, considering the [docs](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration) don't mention anything like that.
